GET http://localhost:5000/api/groups


###
GET http://localhost:5000/api/groups/1

### 
POST http://localhost:5000/api/groups
Content-Type: application/json

{
  "name": "First group",
  "description": "Hello world",
  "created_by_id": 3
}

### 
DELETE http://localhost:5000/api/groups/1

### 
POST http://localhost:5000/api/groups/2/invite
Content-Type: application/json

{
  "user_id": 2
}

