/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as GroupsIndexImport } from './routes/groups/index'
import { Route as GroupsGroupIdTaskManagementImport } from './routes/groups/$groupId/task-management'
import { Route as GroupsGroupIdTaskEditorImport } from './routes/groups/$groupId/task-editor'
import { Route as GroupsGroupIdMessagesImport } from './routes/groups/$groupId/messages'
import { Route as GroupsGroupIdLogInImport } from './routes/groups/$groupId/log-in'
import { Route as GroupsGroupIdInformationHubImport } from './routes/groups/$groupId/information-hub'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const GroupsIndexRoute = GroupsIndexImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => rootRoute,
} as any)

const GroupsGroupIdTaskManagementRoute =
  GroupsGroupIdTaskManagementImport.update({
    id: '/groups/$groupId/task-management',
    path: '/groups/$groupId/task-management',
    getParentRoute: () => rootRoute,
  } as any)

const GroupsGroupIdTaskEditorRoute = GroupsGroupIdTaskEditorImport.update({
  id: '/groups/$groupId/task-editor',
  path: '/groups/$groupId/task-editor',
  getParentRoute: () => rootRoute,
} as any)

const GroupsGroupIdMessagesRoute = GroupsGroupIdMessagesImport.update({
  id: '/groups/$groupId/messages',
  path: '/groups/$groupId/messages',
  getParentRoute: () => rootRoute,
} as any)

const GroupsGroupIdLogInRoute = GroupsGroupIdLogInImport.update({
  id: '/groups/$groupId/log-in',
  path: '/groups/$groupId/log-in',
  getParentRoute: () => rootRoute,
} as any)

const GroupsGroupIdInformationHubRoute =
  GroupsGroupIdInformationHubImport.update({
    id: '/groups/$groupId/information-hub',
    path: '/groups/$groupId/information-hub',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/groups/': {
      id: '/groups/'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsIndexImport
      parentRoute: typeof rootRoute
    }
    '/groups/$groupId/information-hub': {
      id: '/groups/$groupId/information-hub'
      path: '/groups/$groupId/information-hub'
      fullPath: '/groups/$groupId/information-hub'
      preLoaderRoute: typeof GroupsGroupIdInformationHubImport
      parentRoute: typeof rootRoute
    }
    '/groups/$groupId/log-in': {
      id: '/groups/$groupId/log-in'
      path: '/groups/$groupId/log-in'
      fullPath: '/groups/$groupId/log-in'
      preLoaderRoute: typeof GroupsGroupIdLogInImport
      parentRoute: typeof rootRoute
    }
    '/groups/$groupId/messages': {
      id: '/groups/$groupId/messages'
      path: '/groups/$groupId/messages'
      fullPath: '/groups/$groupId/messages'
      preLoaderRoute: typeof GroupsGroupIdMessagesImport
      parentRoute: typeof rootRoute
    }
    '/groups/$groupId/task-editor': {
      id: '/groups/$groupId/task-editor'
      path: '/groups/$groupId/task-editor'
      fullPath: '/groups/$groupId/task-editor'
      preLoaderRoute: typeof GroupsGroupIdTaskEditorImport
      parentRoute: typeof rootRoute
    }
    '/groups/$groupId/task-management': {
      id: '/groups/$groupId/task-management'
      path: '/groups/$groupId/task-management'
      fullPath: '/groups/$groupId/task-management'
      preLoaderRoute: typeof GroupsGroupIdTaskManagementImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/groups': typeof GroupsIndexRoute
  '/groups/$groupId/information-hub': typeof GroupsGroupIdInformationHubRoute
  '/groups/$groupId/log-in': typeof GroupsGroupIdLogInRoute
  '/groups/$groupId/messages': typeof GroupsGroupIdMessagesRoute
  '/groups/$groupId/task-editor': typeof GroupsGroupIdTaskEditorRoute
  '/groups/$groupId/task-management': typeof GroupsGroupIdTaskManagementRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/groups': typeof GroupsIndexRoute
  '/groups/$groupId/information-hub': typeof GroupsGroupIdInformationHubRoute
  '/groups/$groupId/log-in': typeof GroupsGroupIdLogInRoute
  '/groups/$groupId/messages': typeof GroupsGroupIdMessagesRoute
  '/groups/$groupId/task-editor': typeof GroupsGroupIdTaskEditorRoute
  '/groups/$groupId/task-management': typeof GroupsGroupIdTaskManagementRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/groups/': typeof GroupsIndexRoute
  '/groups/$groupId/information-hub': typeof GroupsGroupIdInformationHubRoute
  '/groups/$groupId/log-in': typeof GroupsGroupIdLogInRoute
  '/groups/$groupId/messages': typeof GroupsGroupIdMessagesRoute
  '/groups/$groupId/task-editor': typeof GroupsGroupIdTaskEditorRoute
  '/groups/$groupId/task-management': typeof GroupsGroupIdTaskManagementRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/groups'
    | '/groups/$groupId/information-hub'
    | '/groups/$groupId/log-in'
    | '/groups/$groupId/messages'
    | '/groups/$groupId/task-editor'
    | '/groups/$groupId/task-management'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/groups'
    | '/groups/$groupId/information-hub'
    | '/groups/$groupId/log-in'
    | '/groups/$groupId/messages'
    | '/groups/$groupId/task-editor'
    | '/groups/$groupId/task-management'
  id:
    | '__root__'
    | '/'
    | '/groups/'
    | '/groups/$groupId/information-hub'
    | '/groups/$groupId/log-in'
    | '/groups/$groupId/messages'
    | '/groups/$groupId/task-editor'
    | '/groups/$groupId/task-management'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GroupsIndexRoute: typeof GroupsIndexRoute
  GroupsGroupIdInformationHubRoute: typeof GroupsGroupIdInformationHubRoute
  GroupsGroupIdLogInRoute: typeof GroupsGroupIdLogInRoute
  GroupsGroupIdMessagesRoute: typeof GroupsGroupIdMessagesRoute
  GroupsGroupIdTaskEditorRoute: typeof GroupsGroupIdTaskEditorRoute
  GroupsGroupIdTaskManagementRoute: typeof GroupsGroupIdTaskManagementRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GroupsIndexRoute: GroupsIndexRoute,
  GroupsGroupIdInformationHubRoute: GroupsGroupIdInformationHubRoute,
  GroupsGroupIdLogInRoute: GroupsGroupIdLogInRoute,
  GroupsGroupIdMessagesRoute: GroupsGroupIdMessagesRoute,
  GroupsGroupIdTaskEditorRoute: GroupsGroupIdTaskEditorRoute,
  GroupsGroupIdTaskManagementRoute: GroupsGroupIdTaskManagementRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/groups/",
        "/groups/$groupId/information-hub",
        "/groups/$groupId/log-in",
        "/groups/$groupId/messages",
        "/groups/$groupId/task-editor",
        "/groups/$groupId/task-management"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/groups/": {
      "filePath": "groups/index.tsx"
    },
    "/groups/$groupId/information-hub": {
      "filePath": "groups/$groupId/information-hub.tsx"
    },
    "/groups/$groupId/log-in": {
      "filePath": "groups/$groupId/log-in.tsx"
    },
    "/groups/$groupId/messages": {
      "filePath": "groups/$groupId/messages.tsx"
    },
    "/groups/$groupId/task-editor": {
      "filePath": "groups/$groupId/task-editor.tsx"
    },
    "/groups/$groupId/task-management": {
      "filePath": "groups/$groupId/task-management.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
